Derive MonadFix for labelled effects
fused-effects/fused-effects pull request #402
Opened 2020-12-03 21:08 UTC by JaSpa

All other carriers already define a conditional `MonadFix` instance.

These instances should probably get a `@since XX` annotation and maybe an entry in the changelog. What is your process in that regard? I can add those if you can tell me what the next version number will be or alternatively add some kind of placeholder to fill in when the next release is done.

2020-12-07 14:38 UTC, robrix commented
For the CI failures, merging `master` should suffice.

There aren’t any other changes pending on `master`, so we’ll release this as 1.1.1. `@since 1.1.1` annotations and a changelog entry would be much appreciated, thank you!

2020-12-07 14:39 UTC, robrix requested changes

2020-12-07 14:39 UTC, robrix commented on src/Control/Effect/Labelled.hs
> +  deriving (Alternative, Applicative, Functor, Monad, Fail.MonadFail, MonadIO, MonadPlus, MonadFix, MonadTrans)
Could you please keep this alphabetized (by class name)? i.e. insert `MonadFix` between `Fail.MonadFail` and `MonadIO`.

2020-12-07 14:39 UTC, robrix commented on src/Control/Effect/Labelled.hs
> +  deriving (Alternative, Applicative, Functor, Monad, Fail.MonadFail, MonadIO, MonadPlus, MonadFix)
Ditto here.

2020-12-09 16:44 UTC, JaSpa commented
@robrix I added the `@since` annotations and a changelog entry.

2020-12-09 16:46 UTC, JaSpa commented on src/Control/Effect/Labelled.hs
> +    )
I think breaking this into multiple lines is cleaner than an inline comment `…, MonadFix {- ^ @since 1.1.1 -}, …`

2020-12-10 14:06 UTC, robrix approved these changes
❤️ perfect, thank you so much!

2020-12-10 14:06 UTC, merged

2020-12-10 14:18 UTC, robrix commented
[1.1.1](https://hackage.haskell.org/package/fused-effects-1.1.1.0) has been released!