Add MonadMask, MonadCatch, MonadThrow, and MonadUnliftIO instances
fused-effects/fused-effects pull request #406
Opened 2020-12-13 13:12 UTC by ocharles

An implementation of the suggestion in https://github.com/fused-effects/fused-effects/issues/404. I also added MonadUnliftIO as the same argument applies, and it has an even lighter dependency footprint.

2021-04-07 21:48 UTC, patrickt commented
Sorry for the delay on this! I’m inclined to push back on this one—I think adding two dependencies isn’t worth it given that all the monads from `transformers` have instances. What do you think, @robrix?

2021-04-07 22:02 UTC, evanrelf requested changes
Unfortunately you can't just derive `MonadUnliftIO`. [From the example in docs](https://hackage.haskell.org/package/unliftio-core-0.2.0.1/docs/Control-Monad-IO-Unlift.html#v:wrappedWithRunInIO):

```haskell
newtype AppT m a = AppT { unAppT :: ReaderT Int (ResourceT m) a }
  deriving (Functor, Applicative, Monad, MonadIO)
  -- Unfortunately, deriving MonadUnliftIO does not work.

instance MonadUnliftIO m => MonadUnliftIO (AppT m) where
  withRunInIO = wrappedWithRunInIO AppT unAppT
```

2021-04-08 13:45 UTC, ocharles commented
@evanrelf I don't think that's true as of https://github.com/fpco/unliftio/issues/55 (which is part of `unliftio-core-0.2`)

2021-04-08 13:46 UTC, ocharles commented
@patrickt That may be true, but it means that users of `fused-effects` have to double _their_ dependencies. Sure, it's a boot dependency, but it's kind of annoying that I can't just depend on `fused-effects`. I think that's ultimately what I was trying to do (but it's been so long, I've forgot!)

2021-04-08 15:57 UTC, evanrelf commented
@ocharles Ah you're right, my bad. I guess the docs are just outdated.

2022-02-28 22:25 UTC, robrix commented
First off, thank you for the PR!

I'm 👎🏻 on adding the dependencies and the instances. We offer `Algebra` instances for `transformers` types, and to the best of my knowledge, the majority (if not all) of the functionality provided by the `Monad…` instances can also be provided "natively" via `fused-effects` alone.

@ocharles: I'm still open to discussion, but will close this PR out for the time being; happy to reopen if we conclude counter to the above.

2022-02-28 22:25 UTC, closed without merging