Instances for Choosing
fused-effects/fused-effects pull request #419
Opened 2022-02-27 21:09 UTC by robrix

This PR defines/derives a number of instances for `Control.Effect.Choose.Choosing`.

2022-02-28 13:34 UTC, patrickt approved these changes

2022-02-28 13:36 UTC, patrickt requested changes
Oh, wait, can you add a Changelog entry?

2022-02-28 22:12 UTC, robrix commented
@patrickt: Good catch. Changelog entry added.

2022-03-02 16:43 UTC, patrickt approved these changes

2022-03-02 16:43 UTC, merged