Add MonadUnliftIO instances for eligible carrier types.
fused-effects/fused-effects pull request #420
Opened 2022-02-28 13:33 UTC by patrickt

As per @shinzui and @ocharles's request, and given that `unliftio-core` has a
very small dependency footprint, we've decided to add `MonadUnliftIO` instances.

/hattip @ocharles for demonstrating that `InterpretC` supports this in #408.

2022-02-28 15:38 UTC, shinzui commented
Thank you, @patrickt.

2022-02-28 22:31 UTC, robrix requested changes
Looking good! Just a few notes.

2022-02-28 22:31 UTC, robrix commented on ChangeLog.md
> +# v1.1.2.0
Please don't specify the version number until we're making the release PR; t creates more work if we decide to make a breaking change or rename the version for PR purposes 🧐

2022-02-28 22:31 UTC, robrix commented on ChangeLog.md
> +- Adds `MonadUnliftIO` instances for `ReaderC`, `LiftC`, and `InterpretC`.
That seems exhaustive, to my fuzzy recollection.

2022-02-28 22:31 UTC, robrix commented on src/Control/Carrier/Interpret.hs
> +import Control.Monad.IO.Unlift (MonadUnliftIO)
Whichever of this PR and #419 gets merged first should make sure to derive an instance for `Choosing` as well.

2022-02-28 22:31 UTC, robrix commented on src/Control/Carrier/Reader.hs
> +    withRunInIO $ \run ->
💄 spaces after the `\`s, please.

2022-02-28 22:31 UTC, robrix commented on src/Control/Carrier/Reader.hs
> +  {-# INLINE withRunInIO #-}
💄 `INLINE` directive after the method it applies to, please.

2022-02-28 22:36 UTC, robrix requested changes
Forgot this one.

2022-02-28 22:36 UTC, robrix commented on ChangeLog.md
> +- Adds `MonadUnliftIO` instances for `ReaderC`, `LiftC`, and `InterpretC`.
```suggestion
- Adds `MonadUnliftIO` instances for `ReaderC`, `LiftC`, and `InterpretC`. ([#420](https://github.com/fused-effects/fused-effects/pull/420))
```

2022-03-01 14:12 UTC, robrix commented on src/Control/Carrier/Interpret.hs
> +import Control.Monad.IO.Unlift (MonadUnliftIO)
…and should note it in the changelog.

2022-03-02 16:11 UTC, robrix approved these changes

2022-03-02 16:12 UTC, merged